export const ActionConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_ERROR: 'PROFILE_ERROR',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',

  LOCATION_REQUEST: 'LOCATION_REQUEST',
  LOCATION_SUCCESS: 'LOCATION_SUCCESS',

  PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  PROFILE_UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',

  PROFILE_FLUSH: 'PROFILE_FLUSH',

  GENERATE_OTP_REQUEST: 'GENERATE_OTP_REQUEST',
  GENERATE_OTP_ERROR: 'GENERATE_OTP_ERROR',
  GENERATE_OTP_SUCCESS: 'GENERATE_OTP_SUCCESS',

  //Broker List

  CUSTOMERS_LIST_REQUEST: 'CUSTOMERS_LIST_REQUEST',
  CUSTOMERS_LIST_SUCCESS: 'CUSTOMERS_LIST_SUCCESS',
  CUSTOMERS_LIST_ERROR: 'CUSTOMERS_LIST_ERROR',

  STATUS_CHANGE_REQUEST: 'STATUS_CHANGE_REQUEST',
  STATUS_CHANGE_SUCCESS: 'STATUS_CHANGE_SUCCESS',
  STATUS_CHANGE_ERROR: 'STATUS_CHANGE_ERROR',

  CREATE_CONNECTION: 'CREATE_CONNECTION',
  EMIT_CONNECTION: 'EMIT_CONNECTION',
  LISTEN_CONNECTION: 'LISTEN_CONNECTION',

  SOCKET_CONNECTION: 'SOCKET_CONNECTION',
  SOCKET_DISCONNECT: 'SOCKET_DISCONNECT',
  SOCKET_FLUSH: 'SOCKET_FLUSH',

  NOTIFICATION_REQUEST: 'NOTIFICATION_REQUEST',
  NOTIFICATION_SUCCESS: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_ERROR: 'NOTIFICATION_ERROR',
};
